# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: M7vDRWBJW1EAGzih
    ports:
        - 3306:3306
    volumes:
      - ".\\project4dbscript.sql:/root/project4dbscript.sql"

  tomcat:
    depends_on:
      - db
    image: tomcat
    container_name: tomcat9
    volumes:
      - ".\\webapps:/usr/local/tomcat/webapps"
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: M7vDRWBJW1EAGzih
      MYSQL_DATABASE: project4